CREATE TABLE GRUPO
(
	id_grupo VARCHAR2(10),
	descripcion VARCHAR2(250),
	CONSTRAINT PK_GRUPO PRIMARY KEY (id_grupo)	
);

CREATE TABLE ALUMNO
(
	dni VARCHAR2(10),
	nombre VARCHAR2(50),
	apellido VARCHAR2(50),
	edad NUMBER(5),
	id_grupo VARCHAR2(10),
	CONSTRAINT PK_ALUMNO PRIMARY KEY (dni),
	CONSTRAINT FK_GRUPO FOREIGN KEY (id_grupo) REFERENCES GRUPO(id_grupo)
);